---
language: python
python: "2.7"
env:
  matrix:
    - ANSIBLE_VERSION="1.9.4"
    - ANSIBLE_VERSION="2.0.0.2"

before_install:
 - sudo apt-get update -qq

install:
  - pip install ansible=="$ANSIBLE_VERSION"

script:
  - ansible-galaxy install jdauphant.nginx
  - echo localhost > inventory
  - ansible-playbook -i inventory playbook.yml --syntax-check
  - ansible-playbook -i inventory playbook.yml --connection=local --sudo