---
- name: Create a base server
  hosts: node
  become: yes
  become_user: root
  vars_files:
    - vars/main.yml
    - vars/nvm.yml
    - vars/utilities.yml

  roles:
    - role: utilities
    - role: nvm
    - role: jdauphant.nginx
      nginx_http_params:
        - sendfile "on"
        - access_log "/var/log/nginx/access.log"
      nginx_sites:
        frontend:
           - listen 80
           - server_name autogram.space
           - root /home/deploy/www
           - index index.html
           - location / { try_files $uri$args $uri$args/ $uri $uri/ /index.html =404; }
        backend:
            - listen 80
            - server_name api.autogram.space
            - location / { proxy_pass http://localhost:3000; }
      nginx_configs:
        proxy:
          - proxy_set_header X-Real-IP  $remote_addr
          - proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for