- name: install apt requirements
  become: yes
  apt: pkg=aptitude

- name: update and upgrade apt packages
  apt: >
    upgrade=yes
    update_cache=yes
    cache_valid_time=3600

- name: Install required packages
  apt: state=installed pkg={{ item }}
  with_items: 
  - "{{ utilities }}"
  when: utilities|length > 0

- name: Allow ssh and http(s) connections
  ufw: rule=allow port={{ item }}
  with_items:
    - "{{ ufw_allowed_ports }}"
  when: ufw_allowed_ports|length > 0

- name: Enable ufw/firewall
  ufw: state=enabled policy=deny
  when: ufw_allowed_ports|length > 0

- name: Set up Postfix to relay mail
  debconf: name=postfix
            question='{{ item.question }}'
            value='{{ item.value }}'
            vtype='{{ item.vtype }}'
  with_items:
    - { question: 'postfix/mailname', value: 'feature-deployment', vtype: 'string' }
    - { question: 'postfix/main_mailer_type', value: 'feature', vtype: 'string' }

- name: Email logwatch summary daily
  lineinfile: dest=/etc/cron.daily/00logwatch
              regexp="^/usr/sbin/logwatch"
              line="/usr/sbin/logwatch --output mail --mailto {{ logwatch_email }} --detail high"
              state=present create=yes