- name: Install apt requirements
  become: yes
  apt: state=installed pkg=aptitude

- name: Update and upgrade apt packages
  apt: >
    upgrade=yes
    update_cache=yes
    cache_valid_time=3600

- name: Install unattended-upgrades
  apt: state=installed pkg=unattended-upgrades

- name: Install debconf
  apt: state=installed pkg=debconf