- name: Install fail2ban
  apt: state=installed pkg=fail2ban

- name: Install ufw
  apt: state=installed pkg=ufw

- name: Allow ssh and http(s) connections
  ufw: rule=allow port={{ item }}
  with_items:
    - "{{ ufw_allowed_ports }}"
  when: ufw_allowed_ports|length > 0

- name: Enable ufw/firewall
  ufw: state=enabled policy=deny
  when: ufw_allowed_ports|length > 0

- name: Install logwatch
  apt: state=installed pkg=logwatch

- name: Set up Postfix to relay mail
  debconf: name=postfix
            question='{{ item.question }}'
            value='{{ item.value }}'
            vtype='{{ item.vtype }}'
  with_items:
    - { question: 'postfix/mailname', value: '{{ ansible_fqdn }}', vtype: 'string' }
    - { question: 'postfix/main_mailer_type', value: 'Internet Site', vtype: 'string' }

- name: Email logwatch summary daily
  lineinfile: dest=/etc/cron.daily/00logwatch
              regexp="^/usr/sbin/logwatch"
              line="/usr/sbin/logwatch --output mail --mailto {{ logwatch_email }} --detail high"
              state=present create=yes